name: build-and-test
on:
  push:
    branches:
      - '**'
  pull_request: {}
  schedule:
    - cron: 15 4 * * *
jobs:
  build_and_test:
    strategy:
      matrix:
        zig-version: ['master']

    runs-on: ubuntu-latest
    name: Test / Zig ${{ matrix.zig-version }}
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ matrix.zig-version }}
      - run: zig fmt --check ./*.zig src/*.zig
      - run: zig build test
      - run: zig build test --release=fast
      - run: zig build
